repos:
- repo: local
  hooks:
    - id: terraform_fmt
      name: Terraform Format
      entry: bash -c 'terraform fmt -recursive >/dev/null'
      language: system
      pass_filenames: false
      stages: [pre-commit]

- repo: https://github.com/bridgecrewio/checkov.git
  rev: 3.3.15
  hooks:
    - id: checkov
      name: Checkov
      args:
        - --directory
        - .
        - --framework
        - terraform
        - --skip-path
        - examples
        - --skip-check
        - CKV2_AWS_12
        - --quiet
        - --compact
      pass_filenames: false
      stages: [pre-commit]
